services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - order-service

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo/tempo-config.yml"]
    ports:
      - "3200:3200"
      - "4319:4317"
    volumes:
      - ./tempo/tempo-config.yml:/etc/tempo/tempo-config.yml:ro

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otelcol/config.yml:ro
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    depends_on:
      - prometheus
      - loki
      - tempo

  order-service:
    build:
      context: ../demo_services/order_service
    environment:
      SERVICE_NAME: order-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      LOKI_URL: http://loki:3100
    ports:
      - "8002:8002"
    depends_on:
      - loki
      - otel-collector
